version: 2.1

orbs:
  codecov: codecov/codecov@5.2.1

executors:
  linux:
    docker:
      - image: cimg/android:2025.03.1

jobs:
  upload-coverage:
    executor: linux
    steps:
      - checkout
      - run: ./gradlew jacocoTestReport
      - codecov/upload

workflows:
  build:
    jobs:
      - upload-coverage
