const val RELEASE_USER = "hendraanggrian"
const val RELEASE_GROUP = "com.$RELEASE_USER"
const val RELEASE_ARTIFACT = "socialview"
const val RELEASE_VERSION = "0.18"
const val RELEASE_DESC = "Android TextView and EditText with hashtag, mention, and hyperlink support"
const val RELEASE_WEBSITE = "https://github.com/$RELEASE_USER/$RELEASE_ARTIFACT"